### ISSUE TITLE
Build from source failed 

### ISSUE THREAD

**Issue by IdentySergey** [arenadata/pxf-archive#98]
**Build local is not possible, broken**:
https://github.com/arenadata/pxf/blob/pxf-6.x/server/build.gradle

Added private repositories:
```
maven {
    url "https://rt.adsw.io/artifactory/maven-arenadata-release/"
    mavenContent {
        releasesOnly()
    }
}
maven {
    url "https://rt.adsw.io/artifactory/maven-arenadata-snapshot/"
    mavenContent {
        snapshotsOnly()
    }
}
```

**Comment by RomaZe** [comment]
@IdentySergey Hello! The issue has been resolved and the changes have been merged into the pxf-6.x branch
